#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ -f /usr/local/car/bin/car.py ] 
then 
    echo -e "" 
    exit 0 
else
    echo -e ""
fi

chmod u+x /usr/local/car/bin/*
chmod u+x /usr/share/applications/remote.desktop
#cp /usr/share/applications/remote.desktop /etc/xdg/autostart/

if ! grep "@/usr/local/car/bin/remote.sh" /home/pi/.config/lxsession/LXDE-pi/autostart;
then
    echo "@/usr/local/car/bin/remote.sh" >> /home/pi/.config/lxsession/LXDE-pi/autostart
fi

if ! grep "[SeatDefaults]" /etc/lightdm/lightdm.conf;
then
    echo "[SeatDefaults]" >> /etc/lightdm/lightdm.conf
fi

if ! grep "xserver-command=X -s 0 dpms" /etc/lightdm/lightdm.conf;
then
    echo "xserver-command=X -s 0 dpms" >> /etc/lightdm/lightdm.conf
fi

##
#  Отключение отключения экрана.
##

if ! grep "@xset s noblank" /etc/xdg/lxsession/LXDE-pi/autostart;
then
    echo "@xset s noblank" >> /etc/xdg/lxsession/LXDE-pi/autostart
fi

if ! grep "@xset s off" /etc/xdg/lxsession/LXDE-pi/autostart;
then
    echo "@xset s off" >> /etc/xdg/lxsession/LXDE-pi/autostart
fi

if ! grep "@xset -dpms" /etc/xdg/lxsession/LXDE-pi/autostart;
then
    echo "@xset -dpms" >> /etc/xdg/lxsession/LXDE-pi/autostart
fi

if ! grep "@xset s noblank" /etc/xdg/lxsession/LXDE/autostart;
then
    echo "@xset s noblank" >> /etc/xdg/lxsession/LXDE/autostart
fi

if ! grep "@xset s off" /etc/xdg/lxsession/LXDE/autostart;
then
    echo "@xset s off" >> /etc/xdg/lxsession/LXDE/autostart
fi

if ! grep "@xset -dpms" /etc/xdg/lxsession/LXDE/autostart;
then
    echo "@xset -dpms" >> /etc/xdg/lxsession/LXDE/autostart
fi


ldconfig
exit 0
